include::./SES_vars.adoc[]

==== {sesProductName}

A product offering of the {suseHomePage}[{companyName}](R) portolio is {sesProductPage}[{sesProductName}], an intelligent software-defined storage solution, powered by Ceph technology, which enables you to transform your enterprise storage infrastructure:

* Providing IT organizations with a simple to manage, agile infrastructure with increased speed of delivery, durability and reliability.
* Accelerating innovation, reduce costs and alleviate proprietary hardware lock-in by transforming your enterprise storage infrastructure with a truly open, and unified intelligent software-defined storage solution. 
* Offering ubiquitous and universal access to your legacy and modern applications and automated durability for your data with high availability, performant, secure and disaster recovery options.
* FixMe - Support, Updates/Upgrades Enterprise

FixMe - While a software-defined storage approach may seem new, the logic within enterprise storage devices has always been written in software. It’s only been in the last few years that hardware has progressed enough so that enterprise storage software and dedicated hardware can now be distinctly layered components. Given the enablement and support of the underlying OS, 

FixMe - SES7 Release claims/updates

FixMe - Deployment options

FixMe - Commmunity contributions


