
[glossary]
== Glossary

* Deployment Scenario(s) :
+
ifdef::Balance[]
[[G_Balance]]Balance::
Residing as an intermediary deployment path between pure capacity or performance optimizations, a balanced approach often provides an overlapping subset of each. For new technology adoption efforts, it might be a multi-faceted starting point addressing diverse functions and requirements. As time passes and the chosen technology permits, such a balanced approach remain the foundational solution depending upon the weights and priorities of the use cases.
endif::Balance[]
+
ifdef::CapOpt[]
[[G_CapOpt]]Capacity-Optimized footnote:Capacity-Optimized[link: https://en.wikipedia.org/wiki/Capacity_management[Capacity Management]]::
The goal of capacity optimization is to ensure the right amount of resources to meet both current and future requirements in a cost-effective manner. Given the typical exponential growth curves, it is imperative to evaluate and select a technology that permits migration from previous, existing platforms, that allows for expansion both in size and functionality and that potentially can incorporate newer resources as they become available.
endif::CapOpt[]
+
ifdef::PerfOpt[]
[[G_PerfOpt]]Performance Optimized::
When the primary objective is performance optimized, there are often significant tradeoffs to address any other use cases, the overall efficiency and some potential impacts across resource limitations. Over the lifecycle of the solution, one must do specific exercises around regular platform tuning, bottleneck avoidance, and continually measuring performance, to avoid regression when change are implemented.
endif::PerfOpt[]
+
* Deployment Type(s) :
+
ifdef::cephadm[]
[[G_cephadm]]cephadm footnote:cephadm[link: https://ceph.io/ceph-management/introducing-cephadm/[cephadm]]::
Cephadm provides a fully-featured, robust, and well-maintained install and management layer that can be used for anyone that is not running Ceph in Kubernetes. It includes deploying all components in containers and integration with the Ceph orchestrator API, plus migration from previous deployment tools and helping to automate Ceph clusters and services.
endif::cephadm[]
+
ifdef::Rook[]
[[G_Rook]]Rook footnote:Rook[link: https://rook.io/[Rook]]::
An open-source, cloud-native storage for Kubernetes, providing block devices, filesystems or S3/Swift APIs for object storage. The Rook operator automates configuration of storage components and monitors the cluster to ensure the storage remains available and healthy. It initializes, bootstraps and maintains the Ceph monitors, the Ceph OSD daemons and other pods and artifacts necessary to run the services.
endif::Rook[]

* Factor(s) :
+
ifdef::Availability[]
[[G_Availability]]Availability footnote:Availability[link: https://en.wikipedia.org/wiki/Minimum_viable_product[Availability]]::
The probability that an item operates satisfactorily, without failures or downtimes, under stated conditions as a function of its reliability, redundancy and maintainability attributes. Some major objectives to achieve a desired service level objectives are:
+
** Preventing or reducing the likelihood and frequency of failures via design decisions within the allowed cost of ownership
** Correcting or coping with possible component failures via resiliency, automated failover and disaster-recovery processes
** Estimating and analyzing current conditions to prevent unexpected failures via predictive maintenance
endif::Availability[]
+
ifdef::Integrity[]
[[G_Integrity]]Integrity footnote:Integrity[link: https://en.wikipedia.org/wiki/Data_integrity[Data Integrity]]::
Integrity is the maintenance of, and the insurance of the accuracy and consistency of a specific element over its entire lifecycle. Both physical and logical aspects must be managed to ensure stability, performance, re-usability and maintainability.
endif::Integrity[]
+
ifdef::Performance[]
[[G_Performance]]Performance footnote:Performance[link: https://en.wikipedia.org/wiki/Performance_engineering[Performance Engineering]]::
In the context of a system's expected life cycle, performance is an assessment of transactions, responsiveness and underlying stability of the provider technology while doing tuning and adjustments. Other risk factors and discerning potential impacts to surrounding use cases are also integral parts of the profile to address beyond service levels, capacity and problem managmement.
endif::Performance[]
+
ifdef::Security[]
[[G_Security]]Security footnote:Security[link: https://en.wikipedia.org/wiki/Security[Security]]::
Security is about ensuring freedom from or resilience against potential harm, including protection from destructive or hostile forces. To minimize risks, one mus manage governance to avoid tampering, maintain access controls to prevent unauthorized usage and integrate layers of defense, reporting and recovery tactics.
endif::Security[]

* Flavor(s) :
+
ifdef::PoC[]
// [[G_PoC]]Proof-of-Concept::
[[G_PoC]]Proof-of-Concept footnote:Proof-of-Concept[link: https://en.wikipedia.org/wiki/Proof_of_concept[Proof of Concept]]::
A partial or nearly complete prototype constructed to demonstrate functionality and feasibility for verifying specific aspects or concepts under consideration. This is often a starting point when evaluating a new, transitional technology. Sometimes it starts as a Minimum-Viable-Product footnote:Minimum-Viable-Product[link: https://en.wikipedia.org/wiki/Minimum_viable_product[Minimum Viable Product]] (MVP) that has just enough features to satisfy an initial set of requests. After such insights and feedback are obtained and potentially addressed, redeployments may be utilized to iteratively branch into other realms or to incorporate other known working functionality.
endif::PoC[]
+
ifdef::Production[]
[[G_Production]]Production::
A deployed environment that target customers or users can interact with and rely upon to meet their needs, plus be operationally sustainable in terms of resource utilization and economic constraints.
endif::Production[]
+
ifdef::Scaling[]
[[G_Scaling]]Scaling footnote:Scaling[link: https://en.wikipedia.org/wiki/Scalability[Scalability]]::
The flexibility of a system environment to either vertically scale-up, horizontally scale-out or conversely scale-down by adding or subtracting resources as needed. Attributes like capacity and performance are often the primary requirements to address, while still maintaining functional consistency and reliability.
endif::Scaling[]

