
include::./SA_vars.adoc[]

= {title}
{author}, {companyName} < {authorEMail} >

:favicon:
:doctype: book

[preface]
= Preface

Whether you are just starting or continuing to progress on a digital transformation journey, you should consider addressing one of the core infrastructure elements -- storage. Using this solution architecture, you will learn how to successfully and effectively accomplish this transition with simplify, modernize and accelerate process steps for your software-defined storage.

The following, layered footnote:Archimate[link: https://pubs.opengroup.org/architecture/archimate3-doc[Archimate Enterprise Architecture]] aspects will be covered:

ifdef::Strategy[]
* *_Why_* one should consider this strategy
endif::Strategy[]
ifdef::Business[]
* *_Who_* to engage with, inform and collaborate with
* *_What_* key factors are important and *_When_* to consider them
endif::Business[]
ifdef::Application[]
* *_What_* software and applications this is relevant to accomplish
endif::Application[]
ifdef::Technology[]
* *_How_* various technology components can facilitate this
endif::Technology[]
ifdef::Physical[]
* *_Where_* the resulting solution may physically or virtually reside
endif::Physical[]

Additional characteristics, like decision factors such as:

ifdef::Availability[]
* availability
endif::Availability[]
ifdef::Performance[]
* performance
endif::Performance[]
ifdef::Security[]
* security
endif::Security[]
ifdef::Integrity[]
* integrity
endif::Integrity[]

are also described and incorporated in the respective layers.  Deployment aspect flavors along the lines of

ifdef::PoC[]
* proof-of-concept
endif::PoC[]
ifdef::Production[]
* production
endif::Production[]
ifdef::Scaling[]
* scaling
endif::Scaling[]
ifdef::Migration[]
* migration
endif::Migration[]

implementations and considerations may also be covered.

// Introduction
include::./i-Introduction/SA.adoc[]

// Strategy
ifdef::Strategy[]
include::./ii-Strategy/SA.adoc[]
endif::Strategy[]

// Business
ifdef::Business[]
include::./iii-Business/SA.adoc[]
endif::Business[]

// Application
ifdef::Application[]
include::./iv-Application/SA.adoc[]
endif::Application[]

// Technology
ifdef::Technology[]
include::./v-Technology/SA.adoc[]
endif::Technology[]

// Physical
ifdef::Physical[]
include::./vi-Physical/SA.adoc[]
endif::Physical[]

// Migration
ifdef::Migration[]
include::./vii-Migration/SA.adoc[]
endif::Migration[]

== Summary

FixMe - incidunt vitae semper quis lectus nulla. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Pretium viverra suspendisse potenti nullam ac. Sit amet purus gravida quis blandit. Interdum velit laoreet id donec ultrices tincidunt arcu. Vel pharetra vel turpis nunc eget. Ultrices eros in cursus turpis. Id donec ultrices tincidunt arcu non sodales neque. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Morbi quis commodo odio aenean sed adipiscing diam. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Eu volutpat odio facilisis mauris sit amet massa.


ifdef::Glossary[]
include::./SA-Glossary.adoc[]
endif::Glossary[]

ifdef::Appendix[]
include::./SA-Appendix.adoc[]
endif::Appendix[]

