
include::./SA_vars.adoc[]

= {title}
{author}, {companyName} < {authorEMail} >

:favicon:
:doctype: book

[preface]
= Preface

Whether you are just starting or continuing to progress on a digital transformation journey, you should consider addressing one of the core infrastructure elements -- storage. Using this solution architecture, you will learn how to successfully and effectively accomplish this software-defined storage itransition with simplify, modernize and accelerate process steps.

The following, layered footnote:Archimate[link: https://pubs.opengroup.org/architecture/archimate3-doc[Archimate Enterprise Architecture]] aspects will be covered:

ifdef::Strategy[]
* *_Why_* one should consider this strategy
endif::Strategy[]
ifdef::Business[]
* *_Who_* to engage with, inform and collaborate with
* *_What_* key factors are important and *_When_* to consider them
endif::Business[]
ifdef::Application[]
* *_What_* software and applications this is relevant to accomplish
endif::Application[]
ifdef::Technology[]
* *_How_* various technology components can facilitate this
endif::Technology[]
ifdef::Physical[]
* *_Where_* the resulting solution may physically or virtually reside
endif::Physical[]

////
Additional characteristics, like decision factors such as:

ifdef::Availability[]
* availability
endif::Availability[]
ifdef::Performance[]
* performance
endif::Performance[]
ifdef::Security[]
* security
endif::Security[]
ifdef::Integrity[]
* integrity
endif::Integrity[]

are also described and incorporated in the respective layers.  Deployment aspect flavors along the lines of

ifdef::PoC[]
* proof-of-concept
endif::PoC[]
ifdef::Production[]
* production
endif::Production[]
ifdef::Scaling[]
* scaling
endif::Scaling[]
ifdef::Migration[]
* migration
endif::Migration[]

implementations and considerations may also be covered.
////

// Introduction
include::./i-Introduction/SA.adoc[]

// Strategy
ifdef::Strategy[]
include::./ii-Strategy/SA.adoc[]
endif::Strategy[]

// Business
ifdef::Business[]
include::./iii-Business/SA.adoc[]
endif::Business[]

// Application
ifdef::Application[]
include::./iv-Application/SA.adoc[]
endif::Application[]

// Technology
ifdef::Technology[]
include::./v-Technology/SA.adoc[]
endif::Technology[]

// Physical
ifdef::Physical[]
include::./vi-Physical/SA.adoc[]
endif::Physical[]

// Migration
ifdef::Migration[]
include::./vii-Migration/SA.adoc[]
endif::Migration[]

== Summary

The right software-defined storage soultion transforms your infrastructure into a durable, reliable enterprise-grade environment. It enables you to simplify management and make significant IT savings as you scale storage in an agile and innovative way.

Simplify::
This software-defined storage solution delivers data management and integration with a diverse set of applications and use cases so you can migrate and optimize your data storage with a cohesive set of tools.

Modernize::
With the ever increasing amount of enterprise data, your requirement for storage capacity may soon be greater than your budget to handle it all. Using software-defined storage, as described in this solution architecture, helps you keep expenses down without sacrificing performance by using off-the-shelf commodity servers and disk drives no matter whether they are in your data center or in the cloud, saving up to 70% in costs right away. These solutions also keep operating costs low by delivering a single unified software-defined storage cluster that handles all your storage needs, reducing the time you dedicate to storage management.

Accelerate::
In addition, overall storage needs are changing quickly. Many enterprises are moving from terabyte to petabyte levels of data. In addition, the applications that need to access this information are running in a diverse and rapidly evolving IT environment. Leveraging this layered solution architecture helps you innovate with higher speed and simplicity by delivering access to the latest technology. A software-defined open source storage management solution, is cost-efficient and able to adapt to changing business and data demands seamlessly. As a result, you can be confident your data will be available for any current and future workloads throughout your digital transition.


ifdef::Glossary[]
include::./SA-Glossary.adoc[]
endif::Glossary[]

ifdef::Appendix[]
include::./SA-Appendix.adoc[]
endif::Appendix[]

// Standard SUSE includes
== Legal Notice
include::./{companyName}/common_sbp_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++

// Standard SUSE Best Practices includes
// :leveloffset: 1
include::./{companyName}/common_gfdl1.2_i.adoc[]

