
include::./varsGlobal.adoc[]

ifdef::env-github[]
:imagesdir: {AuthorGHURL}/images/src/png/
endif::[]

= HOL-1289 : Introduction to Kubernetes
{Author}, {CompanyName} < {AuthorEMail} >

[preface]
== Preface

Ramping up to the Fastlane: A Beginner's Guide to Learning and Using Kubernetes::
Emerging as the defacto standard of orchestrating containerized, microservice workloads, Kubernetes is quickly becoming a fundamental training goala. In this hands-on session, you will learn how to effectively utilize the Kubernetes technology across the various Dev, Security, Data, and Ops perspectives. Starting with a single workload and then working towards a complete, containerized service deployment, you will interact with and explore the features provided by Kubernetes to leverage the scalable, resilient, manageable environment for the workloads.

include::./Lab1.adoc[]
include::./Lab2.adoc[]
include::./Lab3.adoc[]

== Summary (wrap-up with slides, 5 minutes)

At this point you should now feel like you have enough experience with Kubernetes to share with your peers, begin using it on-premise, in managed services or in public cloud providers.

IMPORTANT: help us cleanup the lab environment before you leave

== Homework

If this enticed you to further investigate this technology, feel free to grab all of the lab exercises, plus the technology to deploy your own Kubernetes cluster.
