
include::./vars.adoc[]

= Introduction to Kubernetes HOL-1289
{Author}, {CompanyName} < {AuthorEMail} >

== Ramping up to the Fastlane: A Beginner's Guide to Learning and Using Kubernetes

* Emerging as the defacto standard of orchestrating containerized, microservice workloads, Kubernetes is quickly becoming a fundamental training goala. In this hands-on session, you will learn how to effectively utilize the Kubernetes technology across the various Dev, Security, Data, and Ops perspectives. Starting with a single workload and then working towards a complete, containerized service deployment, you will interact with and explore the features provided by Kubernetes to leverage the scalable, resilient, manageable environment for the workloads.

=== Start Your Engines

* Let us get started with a quick, simple interaction with Kubernetes

=== Turn Signal On, Getting Ready to Merge

* Understanding the basics of how to interact

=== Heading Down the Highway

* Becoming aware of all the aspects around you

== Summary

At this point you should now feel like you have enough experience with Kubernetes to share with your peers, begin using it on-premise, in managed services or in public cloud providers.
