:experimental:

include::./varsGlobal.adoc[]

ifdef::env-github[]
:imagesdir: {AuthorGHURL}/images/src/png/
endif::[]

= HOL-1289 : Introduction to Kubernetes
{Author}, {CompanyName} < {AuthorEMail} >

[preface]
== Preface

Ramping up to the Fastlane: A Beginner's Guide to Learning and Using Kubernetes::
Emerging as the defacto standard of orchestrating containerized, microservice workloads, Kubernetes is quickly becoming a fundamental training objective. In this hands-on session, you will learn how to effectively utilize the Kubernetes technology across the various Dev, Security, Data, and Ops perspectives to leverage the scalable, resilient, manageable environment for the workloads.
+
* In the first lab session, we will start with a single, yet complete containerized service deployment to give you the attraction of using Kubernetes. In essence, you will learn how to start and destroy the deployment with ease.
* In the next lab section, you will learn how to interact with several of these components to address scale, upgrades, and manage the running deployment through its lifecycle stages.
* In the final lab section you will discover many of the traditional IT pillar aspects of Kubernete to help organize, monitor and effectively operate your workload deployments.

include::./conventions.adoc[]

include::./Lab1.adoc[]
include::./Lab2.adoc[]
include::./Lab3.adoc[]

== Summary

As you have likely noticed, this hands-on lab provided exercises

* from a top-down perspective, starting with a complete microservice-based application deployment
* then drilling down through managing and adjusting the deployment through lifecycle attributes
* and digging even deeper to take operational advantage of more functional components, including uncovering the underlying resources involved

At this point you should now feel like you have enough experience with Kubernetes to share with your peers, begin using it on-premise, in managed services or in public cloud providers.

IMPORTANT: help us cleanup the lab environment before you leave

== Homework

If this enticed you to further investigate this technology, feel free to:
* take this lab guide (and even grab the https://github.com/bwgartner/suse-doc/tree/master/SUSECon/2020/HOL-1289[source]) including all of the referenced file content
* https://www.suse.com/download-linux/[download] the https://www.suse.com/products/server/[SUSE Linux Enterprise Server] operating system and https://www.suse.com/products/caas-platform/[SUSE CaaS Platform] and the associated https://documentation.suse.com/[product documentation]
* the technology to https://github.com/alexarnoldy/new_SUSECon[deploy] such a Kubernetes cluster on your own Linux KVM host
