ifndef::EA,RA[]

ifdef::DP+droplet[]
== Droplet - Automation of Collecting Support Configuration

This summarizes how to setup automation for collecting support configuration files, based upon noticing hints or clues of potential changes since the last check.

NOTE:: Of course, a simple run on a given system of supportconfig can generate the basic file collection, which can then be sent to the data puddle.

ifdef::aludo,indico[]
=== Aludo (hint) / Indico (clue)

Simple process: (and video links)

* GitHub (source code)
** git clone https://github.com/bwgartner/aludo
** cd aludo
** review the configuration file (aludo.conf) and adjust as needed
*** to change output/transfer locations
** execute sudo ./bin/aludo and review cited outputs

* Package Repository - https://build.opensuse.org/package/show/home:bwgartner/aludo
** install package (via zypper)
** review the configuration file (aludo.conf) and adjust as needed
*** to change output/transfer locations
** if desired, review the aludo.timer file, adjust the runtime frequency and enable, via systemctl enable --now aludo.timer
** for a manual run, execute sudo /usr/sbin/aludo and review the cited outputs

In essence, this tool looks for various potential hints:clues of system changes since the last run, currently:

* btrfs : snapper status/diff
* systemctl : journalctl

and if found, creates a bundle of a supportconfig plus this hint/clue metadata and transfers it to the designated data puddle.

endif::aludo,indico[]
endif::DP+droplet[]
endif::EA,RA[]

ifdef::EA+Application[]
include::./SA-EA-Application.adoc[]
endif::EA+Application[]

ifdef::RA+ArchOv[]
include::./SA-RA-ArchOv.adoc[]
endif::RA+ArchOv[]
