ifndef::EA,RA[]

ifdef::DP+pond[]
== Data Pond Analytics

This section summarizes how to obtain and run the support config analytics on incoming support config files.

=== Support Config Analytics Package

Packages (sca-L0) are built in {companyName} Internal Build Service (IBS) and provide runtime scripts, susedata, datasets, and extra internal-only dataset. Current sca-L0 dependencies require that sca-datasets and sca-susedata packages be the same version as the sca-L0 package.

* sca-L0 package::
** main runtime package, contains sca-L0 scripts
*** depends on sca-susedata and sca-datasets

* sca-susedata package
** all the SUSE data files (lifecycle info, rpm info, etc.)

* sca-datasets package
** all the datasets

* sca-datasets-suse package
** extra (internal) package containing dataset that maps md5sums to supportconfig names

All of this is based upon a private GitHub project which contains everything needed to get rawdata, get susedata, build datasets, and do actual supportconfig analysis.  Also contains DVC info to manage rawdata and dataset versions.  All scripts have "-h" and "-d" options for help and debug.

* bin directory
** rawdata-* scripts: bash scripts to pull raw bug/SR/cert supportconfigs
** susedata-* scripts: bash scripts to pull package info from SMT/RMT repos
** dataset* scripts: bash and python scripts to build datasets from rawdata
** sca-L0*, knn* scripts: bash and python scripts to analyze supportconfigs  
** other common scripts: bash scripts to extract info from supportconfig files (used at runtime and during dataset build)

* rawdata.dvc
** dvc info to track rawdata versions

* datasets.dvc
** dvc info to track dataset versions

=== Analyzing a supportconfig

To analyze a supportconfig: (add video link)

* Run "sca-L0.sh <supportconfig-tarball>"
** Will uncompress the supportconfig, extract data from it, then report on various features.
** Some features (OS version, support status, etc.) are reported directly.
** Other features are vectorized for nearest-neighbor comparison against datasets.
** Hardware certs are found by doing nearest-neighbor "matching" comparison to the cert datasets.
** SRs/bugs are found by doing nearest-neighbor "jaccard" comparison with multiple warning and error message datasets.
** Comparison handles situation where supportconfig has a new feature that doesn't exist in the datasets.
** Code structure allows for adding other datasets to the comparison and for assigning different weights to different datasets.
** Nearest-neighbor results from all datasets are combined and processed then output is list of "likely" SRs and bugs along with "scores" indicating closeness.

endif::DP+pond[]
endif::EA,RA[]

ifdef::EA+Business[]
include::./SA-EA-Business.adoc[]
endif::EA+Business[]

ifdef::RA+Requirements[]
include::./SA-RA-Requirements.adoc[]
endif::RA+Requirements[]
