
include::../vars.adoc[]


= {CompanyName} {ProductNameContainer} Cluster Installation Process
{Author}, {CompanyName} < {AuthorEMail} >

This process outlines how to install {CompanyName} {ProductNameContainer} {ProductNameContainerVer} on a set of available virtual machines to create a solution cluster in the {IHVPartner} {IHVPartnerEnv}.

NOTE: This document only cites steps, values or inputs which need to be changed from the default, documented process. It also assumes this environment's respective, automated installation process was used and that the quantity nodes, for each role type, are configured to use the correct repositories and are fully patched and updated.

TIP: Refer to respective https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/[{CompanyName} {ProductNameContainer} {ProductNameContainerVer} Deployment Guide] for more complete details. 

== Install the solution cluster
After connecting via the VPN and logging into the jumphost, visit the vSphere Web Client, then follow the steps below:

. Right click on the respective VM "adm.k8s" _Open Remote Console_
. Login to the node as the "{ProductNameContainerUser}" user
* Setup the necessary https://https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#deployment.preparations[Basic SSH Key Configuration]
* Ensure the "{ProductNameContainerUser}" user has https://https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_[sudo access] on all the cluster ndoes
* Then proceed with:
** "Intializing the Cluster" process via
+
----
skuba cluster init --control-plane mstr.k8s.suse.cic my-cluster
----
+
*** "Cluster Bootstrap" via
+
[subs="attributes"]
----
cd my-cluster

skuba node bootstrap --user {ProductNameContainerUser} --sudo --target mstr1.k8s.suse.cic mstr1.k8s

skuba node join --role worker --user {ProductNameContainerUser} --sudo --target wrkr1.k8s.suse.cic wrkr1.k8s
skuba node join --role worker --user {ProductNameContainerUser} --sudo --target wrkr2.k8s.suse.cic wrkr2.k8s
skuba node join --role worker --user {ProductNameContainerUser} --sudo --target wrkr3.k8s.suse.cic wrkr3.k8s
----
+
*** Validate the cluster, via
+
----
skuba cluster status
----
+
And with the steps in https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_using_kubectl["Using kubectl"].

At this point, the {CompanyName} {ProductNameContainer} solution cluster should be up, running and functional.  
