
== Introduction

The growth in data generated and collected by every organization seems to be exceeding even the highest expectations. While there are likely existing answers for mission-critical or transactional data, that is likely less than a quarter of the volume that you will need to store and manage going forward. The remaining portion, becoming a relentless torrent of data capacity to manage, requires organizations to consider a simpler, more scalable and more cost-effective way to store it. The answer lies in an intelligent, software-defined storage footnote:storage[link: https://en.wikipedia.org/wiki/Software-defined_storage[Software-defined storage]] [ {useCase} ] solution that allows you to seamlessly adapt to changing demands. The right {useCase} transforms your storage infrastructure into a durable, performant, secure and reliable enterprise-grade environment. Further, it enables you to simplify management and make significant IT savings as you scale storage in an agile and innovative way.

FixMe - add estimated growth figure

In the following chapters, content includes how this layer provides the necessary attributes to the one above, details and context for this layer itself, and what requirements are needed by the underlying layer. Thus readers are encouraged to scan the entire document to understand the overall solution, even if only expexpected to focus on a certain layer's aspect.

