
== Deployment

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Integer vitae justo eget magna fermentum iaculis eu non diam. Rhoncus urna neque viverra justo. Elementum tempus egestas sed sed risus. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Venenatis a condimentum vitae sapien pellentesque. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Nibh cras pulvinar mattis nunc. Tempor orci dapibus ultrices in iaculis nunc. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Nisi porta lorem mollis aliquam. Laoreet id donec ultrices tincidunt arcu non sodales.

////
The following typographical conventions are used in this manual:
    • /etc/passwd: directory names and file names
    • placeholder: replace placeholder with the actual value
    • PATH: the environment variable PATH
    • Alt, Alt+F1: a key to press or a key combination; keys are shown in uppercase as on a keyboard
    • File, File > Save As: menu items, buttons
    • command line: commands executed in the console
////

=== Deployment overview

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

ifdef::HWDepCfg[]

=== Hardware deployment configuration

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

endif::HWDepCfg[]

ifdef::SWDepCfg[]

=== Software deployment configuration

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

endif::SWDepCfg[]
