
ifdef::IHV-Seagate[]

include::./SA_vars.adoc[]
include::./Exos_vars.adoc[]

=== {companySeagate}

Utilizing the above software application and technology solutions with the server platforms offered by {companySeagate} [ {acronymSeagate} ] provides many alternative for scale, cost-effectiveness and performance options that could align with local IT staff platform preferences:

* density-optimized - high performance and efficiency for big data and the most demanding workloads
* mission-critical - systems of intelligence to fuel your digital transformation in a world where time and data are the new currency and business continuity is expected
* composable - fully adaptable and ready for Hybrid-IT to future-proof your data center for today's workloads and tomorrow's disruptors
* IoT - realize the potential of the Internet of Things to provide compute at the network edge
* cloud - high-capacity, mass-compute open infrastructure with security and software to match
* and virtualized use cases.

ifdef::IHV-Seagate-Exos[]

NOTE: {acronymSeagate} https://techlibrary.hpe.com/us/en/enterprise/servers/supportmatrix/suse_linux.aspx[Servers Support & OS Certification Matrices] outlines the minimum version of SLE required for installation, yet later service pack releases may also be used.

include::../../{companyName}/YES.adoc[]

Server product-line and model options abound in the https://www.hpe.com/uk/en/servers.html[{acronymSeagate} portfolio], including:

ifdef::IHV-Seagate-Exos[]
include::./Exos.adoc[]
endif::IHV-Seagate-Exos[]

==== Suggested Platform Models

Even with the broad certification and support model across the range of available {acronymSeagate} platform models, the following table summarizes which might be a best-practice selection for the various deployment types and sizes (**__S__**mall, **__M__**edium, **__L__**arge, **__XL__**arge).

.{companySeagate} Platform Matrix for Deployment Types
[width="80%",valign="middle",halign="center",options="header"]
|===

| System Platform |
ifdef::CapOpt[ *_<<G_CapOpt,Capacity Optimized>>_* |] 
ifdef::Balance[ *_<<G_Balance,Balance>>_* |] 
ifdef::PerfOpt[ *_<<G_PerfOpt,Performance Optimized>>_* ] 

ifdef::IHV-Seagate-Exos[]
| Apollo
ifdef::CapOpt[|*_(XL) =_* {modelSeagate-A4510}]
ifdef::Balance[|*_(XL) =_* {modelSeagate-A4510} *_(L) =_* {modelSeagate-A4200}]
ifdef::PerfOpt[|*_(L) =_* {modelSeagate-A4200}]
endif::IHV-Seagate-Apollo[]

|===

endif::IHV-Seagate-Exos[]

endif::IHV-Seagate[]
